-- ============================================ --
--  V9: Convert city columns to store enum names --
-- ============================================ --

-- Cập nhật city trong bảng jobs
UPDATE jobs
SET city = CASE city
    WHEN 'An Giang' THEN 'AN_GIANG'
    WHEN 'Bà Rịa - Vũng Tàu' THEN 'BA_RIA_VUNG_TAU'
    WHEN 'Bạc Liêu' THEN 'BAC_LIEU'
    WHEN 'Bắc Giang' THEN 'BAC_GIANG'
    WHEN 'Bắc Kạn' THEN 'BAC_KAN'
    WHEN 'Bắc Ninh' THEN 'BAC_NINH'
    WHEN 'Bến Tre' THEN 'BEN_TRE'
    WHEN 'Bình Dương' THEN 'BINH_DUONG'
    WHEN 'Bình Định' THEN 'BINH_DINH'
    WHEN 'Bình Phước' THEN 'BINH_PHUOC'
    WHEN 'Bình Thuận' THEN 'BINH_THUAN'
    WHEN 'Cà Mau' THEN 'CA_MAU'
    WHEN 'Cao Bằng' THEN 'CAO_BANG'
    WHEN 'Cần Thơ' THEN 'CAN_THO'
    WHEN 'Đà Nẵng' THEN 'DA_NANG'
    WHEN 'Đắk Lắk' THEN 'DAK_LAK'
    WHEN 'Đắk Nông' THEN 'DAK_NONG'
    WHEN 'Điện Biên' THEN 'DIEN_BIEN'
    WHEN 'Đồng Nai' THEN 'DONG_NAI'
    WHEN 'Đồng Tháp' THEN 'DONG_THAP'
    WHEN 'Gia Lai' THEN 'GIA_LAI'
    WHEN 'Hà Giang' THEN 'HA_GIANG'
    WHEN 'Hà Nam' THEN 'HA_NAM'
    WHEN 'Hà Nội' THEN 'HA_NOI'
    WHEN 'Hà Tĩnh' THEN 'HA_TINH'
    WHEN 'Hải Dương' THEN 'HAI_DUONG'
    WHEN 'Hải Phòng' THEN 'HAI_PHONG'
    WHEN 'Hậu Giang' THEN 'HAU_GIANG'
    WHEN 'Hòa Bình' THEN 'HOA_BINH'
    WHEN 'Hồ Chí Minh' THEN 'HO_CHI_MINH'
    WHEN 'Hưng Yên' THEN 'HUNG_YEN'
    WHEN 'Khánh Hòa' THEN 'KHANH_HOA'
    WHEN 'Kiên Giang' THEN 'KIEN_GIANG'
    WHEN 'Kon Tum' THEN 'KON_TUM'
    WHEN 'Lai Châu' THEN 'LAI_CHAU'
    WHEN 'Lạng Sơn' THEN 'LANG_SON'
    WHEN 'Lào Cai' THEN 'LAO_CAI'
    WHEN 'Lâm Đồng' THEN 'LAM_DONG'
    WHEN 'Long An' THEN 'LONG_AN'
    WHEN 'Nam Định' THEN 'NAM_DINH'
    WHEN 'Nghệ An' THEN 'NGHE_AN'
    WHEN 'Ninh Bình' THEN 'NINH_BINH'
    WHEN 'Ninh Thuận' THEN 'NINH_THUAN'
    WHEN 'Phú Thọ' THEN 'PHU_THO'
    WHEN 'Phú Yên' THEN 'PHU_YEN'
    WHEN 'Quảng Bình' THEN 'QUANG_BINH'
    WHEN 'Quảng Nam' THEN 'QUANG_NAM'
    WHEN 'Quảng Ngãi' THEN 'QUANG_NGAI'
    WHEN 'Quảng Ninh' THEN 'QUANG_NINH'
    WHEN 'Quảng Trị' THEN 'QUANG_TRI'
    WHEN 'Sóc Trăng' THEN 'SOC_TRANG'
    WHEN 'Sơn La' THEN 'SON_LA'
    WHEN 'Tây Ninh' THEN 'TAY_NINH'
    WHEN 'Thái Bình' THEN 'THAI_BINH'
    WHEN 'Thái Nguyên' THEN 'THAI_NGUYEN'
    WHEN 'Thanh Hóa' THEN 'THANH_HOA'
    WHEN 'Thừa Thiên Huế' THEN 'THUA_THIEN_HUE'
    WHEN 'Tiền Giang' THEN 'TIEN_GIANG'
    WHEN 'Trà Vinh' THEN 'TRA_VINH'
    WHEN 'Tuyên Quang' THEN 'TUYEN_QUANG'
    WHEN 'Vĩnh Long' THEN 'VINH_LONG'
    WHEN 'Vĩnh Phúc' THEN 'VINH_PHUC'
    WHEN 'Yên Bái' THEN 'YEN_BAI'
    ELSE NULL
END;

-- Cập nhật city trong bảng companies
UPDATE companies
SET city = CASE city
    WHEN 'An Giang' THEN 'AN_GIANG'
    WHEN 'Bà Rịa - Vũng Tàu' THEN 'BA_RIA_VUNG_TAU'
    WHEN 'Bạc Liêu' THEN 'BAC_LIEU'
    WHEN 'Bắc Giang' THEN 'BAC_GIANG'
    WHEN 'Bắc Kạn' THEN 'BAC_KAN'
    WHEN 'Bắc Ninh' THEN 'BAC_NINH'
    WHEN 'Bến Tre' THEN 'BEN_TRE'
    WHEN 'Bình Dương' THEN 'BINH_DUONG'
    WHEN 'Bình Định' THEN 'BINH_DINH'
    WHEN 'Bình Phước' THEN 'BINH_PHUOC'
    WHEN 'Bình Thuận' THEN 'BINH_THUAN'
    WHEN 'Cà Mau' THEN 'CA_MAU'
    WHEN 'Cao Bằng' THEN 'CAO_BANG'
    WHEN 'Cần Thơ' THEN 'CAN_THO'
    WHEN 'Đà Nẵng' THEN 'DA_NANG'
    WHEN 'Đắk Lắk' THEN 'DAK_LAK'
    WHEN 'Đắk Nông' THEN 'DAK_NONG'
    WHEN 'Điện Biên' THEN 'DIEN_BIEN'
    WHEN 'Đồng Nai' THEN 'DONG_NAI'
    WHEN 'Đồng Tháp' THEN 'DONG_THAP'
    WHEN 'Gia Lai' THEN 'GIA_LAI'
    WHEN 'Hà Giang' THEN 'HA_GIANG'
    WHEN 'Hà Nam' THEN 'HA_NAM'
    WHEN 'Hà Nội' THEN 'HA_NOI'
    WHEN 'Hà Tĩnh' THEN 'HA_TINH'
    WHEN 'Hải Dương' THEN 'HAI_DUONG'
    WHEN 'Hải Phòng' THEN 'HAI_PHONG'
    WHEN 'Hậu Giang' THEN 'HAU_GIANG'
    WHEN 'Hòa Bình' THEN 'HOA_BINH'
    WHEN 'Hồ Chí Minh' THEN 'HO_CHI_MINH'
    WHEN 'Hưng Yên' THEN 'HUNG_YEN'
    WHEN 'Khánh Hòa' THEN 'KHANH_HOA'
    WHEN 'Kiên Giang' THEN 'KIEN_GIANG'
    WHEN 'Kon Tum' THEN 'KON_TUM'
    WHEN 'Lai Châu' THEN 'LAI_CHAU'
    WHEN 'Lạng Sơn' THEN 'LANG_SON'
    WHEN 'Lào Cai' THEN 'LAO_CAI'
    WHEN 'Lâm Đồng' THEN 'LAM_DONG'
    WHEN 'Long An' THEN 'LONG_AN'
    WHEN 'Nam Định' THEN 'NAM_DINH'
    WHEN 'Nghệ An' THEN 'NGHE_AN'
    WHEN 'Ninh Bình' THEN 'NINH_BINH'
    WHEN 'Ninh Thuận' THEN 'NINH_THUAN'
    WHEN 'Phú Thọ' THEN 'PHU_THO'
    WHEN 'Phú Yên' THEN 'PHU_YEN'
    WHEN 'Quảng Bình' THEN 'QUANG_BINH'
    WHEN 'Quảng Nam' THEN 'QUANG_NAM'
    WHEN 'Quảng Ngãi' THEN 'QUANG_NGAI'
    WHEN 'Quảng Ninh' THEN 'QUANG_NINH'
    WHEN 'Quảng Trị' THEN 'QUANG_TRI'
    WHEN 'Sóc Trăng' THEN 'SOC_TRANG'
    WHEN 'Sơn La' THEN 'SON_LA'
    WHEN 'Tây Ninh' THEN 'TAY_NINH'
    WHEN 'Thái Bình' THEN 'THAI_BINH'
    WHEN 'Thái Nguyên' THEN 'THAI_NGUYEN'
    WHEN 'Thanh Hóa' THEN 'THANH_HOA'
    WHEN 'Thừa Thiên Huế' THEN 'THUA_THIEN_HUE'
    WHEN 'Tiền Giang' THEN 'TIEN_GIANG'
    WHEN 'Trà Vinh' THEN 'TRA_VINH'
    WHEN 'Tuyên Quang' THEN 'TUYEN_QUANG'
    WHEN 'Vĩnh Long' THEN 'VINH_LONG'
    WHEN 'Vĩnh Phúc' THEN 'VINH_PHUC'
    WHEN 'Yên Bái' THEN 'YEN_BAI'
    ELSE NULL
END;
